#! /bin/sh
# TODO: Factor this into its own file
primary_monitor="$(xrandr -q | grep primary | awk 'NR==1{print $1}')"
monitors=$(xrandr --listactivemonitors | awk 'NR>1 {print $NF}')
resolution=$(xrandr --current | grep "\*" | awk '{print $1}')
resolution_width=$(echo "$resolution" | awk -F 'x' '{print $1}')
# resolution_height=$(echo "$resolution" | awk -F 'x' '{print $2}')

bspc monitor "$primary_monitor" -d I II III IV V VI VII
for monitor in $monitors; do
    if [ "$monitor" != "$primary_monitor" ]; then
        bspc monitor "$monitor" -d 1 2 3 4 5 6 7
    fi
done

feh --bg-scale "$HOME/Pictures/Wallpapers/gruvbox/wall_secondary.png"

bspc config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true
#######################

bspc config border_width         2
# bspc config window_gap          12
bspc config top_monocle_padding          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
# Rectangle setting throws errors sometimes
bspc rule -a KeePassXC state=floating follow=off # rectangle="$((resolution_width-20))x$((resolution_height-20))"+10+60 sticky=false hidden=false
bspc rule -a Todoist desktop='^3' follow=off focus=off # rectangle="$((resolution_width-20))x$((resolution_height-66))"+10+60 sticky=false hidden=false
bspc rule -a thunderbird:Mail:* desktop='^4' follow=on # rectangle="$((resolution_width-20))x$((resolution_height-66))"+10+60 sticky=false
bspc rule -a Blueman-manager state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# bspwm directory
scripts_dir=/home/"$(whoami)"/.config/bspwm/
sh -c "$scripts_dir"/scripts/autostart.sh &

if [ "$1" != 0 ];then
    # programs to only run on restarts
    dunstify -t 1500 "bspwm restarted"
else
    # programs to run at start only
    sh -c "$scripts_dir"/scripts/settings.sh &

    # TODO: Set screen temperature without halting wm start
    # redshift -x -O 3000K &

    # daemonize this entire process
    {
        checkupdates && {
            action="$(dunstify -u 1 -A updateAction,update "updates available")"
            if [ "$action" = "updateAction" ];then
                kitty --hold paru
            fi
        }
    } &
fi

