#!/usr/bin/bash
rm -rf /tmp/hypr_sockets/ > /dev/null

if [ ! -d /tmp/hypr_sockets/ ]; then
    mkdir -p /tmp/hypr_sockets
    mkfifo /tmp/hypr_sockets/active_ws
    mkfifo /tmp/hypr_sockets/active_submap
fi
handle() {
    case "$1" in
        "workspace>>1") echo "(box :halign \"start\" (box (button :onclick \"hyprctl dispatch workspace 1\" :css \"button {color: red;}\" \"1\")(button :onclick \"hyprctl dispatch workspace 2\" \"2\")(button :onclick \"hyprctl dispatch workspace 3\" \"3\")(button :onclick \"hyprctl dispatch workspace 4\" \"4\")(button :onclick \"hyprctl dispatch workspace 5\" \"5\")(button :onclick \"hyprctl dispatch workspace 6\" \"6\")(button :onclick \"hyprctl dispatch workspace 7\" \"7\")(button :onclick \"hyprctl dispatch workspace 8\" \"8\")(button :onclick \"hyprctl dispatch workspace 9\" \"9\")(button :onclick \"hyprctl dispatch workspace 10\" \"10\")))" >> /tmp/hypr_sockets/active_ws ;;
        "workspace>>2") echo "(box :halign \"start\" (box (button :onclick \"hyprctl dispatch workspace 1\" \"1\")(button :onclick \"hyprctl dispatch workspace 2\" :css \"button {color: red;}\" \"2\")(button :onclick \"hyprctl dispatch workspace 3\" \"3\")(button :onclick \"hyprctl dispatch workspace 4\" \"4\")(button :onclick \"hyprctl dispatch workspace 5\" \"5\")(button :onclick \"hyprctl dispatch workspace 6\" \"6\")(button :onclick \"hyprctl dispatch workspace 7\" \"7\")(button :onclick \"hyprctl dispatch workspace 8\" \"8\")(button :onclick \"hyprctl dispatch workspace 9\" \"9\")(button :onclick \"hyprctl dispatch workspace 10\" \"10\")))" >> /tmp/hypr_sockets/active_ws ;;
        "workspace>>3") echo "(box :halign \"start\" (box (button :onclick \"hyprctl dispatch workspace 1\" \"1\")(button :onclick \"hyprctl dispatch workspace 2\" \"2\")(button :onclick \"hyprctl dispatch workspace 3\" :css \"button {color: red;}\" \"3\")(button :onclick \"hyprctl dispatch workspace 4\" \"4\")(button :onclick \"hyprctl dispatch workspace 5\" \"5\")(button :onclick \"hyprctl dispatch workspace 6\" \"6\")(button :onclick \"hyprctl dispatch workspace 7\" \"7\")(button :onclick \"hyprctl dispatch workspace 8\" \"8\")(button :onclick \"hyprctl dispatch workspace 9\" \"9\")(button :onclick \"hyprctl dispatch workspace 10\" \"10\")))" >> /tmp/hypr_sockets/active_ws ;;
        "workspace>>4") echo "(box :halign \"start\" (box (button :onclick \"hyprctl dispatch workspace 1\" \"1\")(button :onclick \"hyprctl dispatch workspace 2\" \"2\")(button :onclick \"hyprctl dispatch workspace 3\" \"3\")(button :onclick \"hyprctl dispatch workspace 4\" :css \"button {color: red;}\" \"4\")(button :onclick \"hyprctl dispatch workspace 5\" \"5\")(button :onclick \"hyprctl dispatch workspace 6\" \"6\")(button :onclick \"hyprctl dispatch workspace 7\" \"7\")(button :onclick \"hyprctl dispatch workspace 8\" \"8\")(button :onclick \"hyprctl dispatch workspace 9\" \"9\")(button :onclick \"hyprctl dispatch workspace 10\" \"10\")))" >> /tmp/hypr_sockets/active_ws ;;
        "workspace>>5") echo "(box :halign \"start\" (box (button :onclick \"hyprctl dispatch workspace 1\" \"1\")(button :onclick \"hyprctl dispatch workspace 2\" \"2\")(button :onclick \"hyprctl dispatch workspace 3\" \"3\")(button :onclick \"hyprctl dispatch workspace 4\" \"4\")(button :onclick \"hyprctl dispatch workspace 5\" :css \"button {color: red;}\" \"5\")(button :onclick \"hyprctl dispatch workspace 6\" \"6\")(button :onclick \"hyprctl dispatch workspace 7\" \"7\")(button :onclick \"hyprctl dispatch workspace 8\" \"8\")(button :onclick \"hyprctl dispatch workspace 9\" \"9\")(button :onclick \"hyprctl dispatch workspace 10\" \"10\")))" >> /tmp/hypr_sockets/active_ws ;;
        "workspace>>6") echo "(box :halign \"start\" (box (button :onclick \"hyprctl dispatch workspace 1\" \"1\")(button :onclick \"hyprctl dispatch workspace 2\" \"2\")(button :onclick \"hyprctl dispatch workspace 3\" \"3\")(button :onclick \"hyprctl dispatch workspace 4\" \"4\")(button :onclick \"hyprctl dispatch workspace 5\" \"5\")(button :onclick \"hyprctl dispatch workspace 6\" :css \"button {color: red;}\" \"6\")(button :onclick \"hyprctl dispatch workspace 7\" \"7\")(button :onclick \"hyprctl dispatch workspace 8\" \"8\")(button :onclick \"hyprctl dispatch workspace 9\" \"9\")(button :onclick \"hyprctl dispatch workspace 10\" \"10\")))" >> /tmp/hypr_sockets/active_ws ;;
        "workspace>>7") echo "(box :halign \"start\" (box (button :onclick \"hyprctl dispatch workspace 1\" \"1\")(button :onclick \"hyprctl dispatch workspace 2\" \"2\")(button :onclick \"hyprctl dispatch workspace 3\" \"3\")(button :onclick \"hyprctl dispatch workspace 4\" \"4\")(button :onclick \"hyprctl dispatch workspace 5\" \"5\")(button :onclick \"hyprctl dispatch workspace 6\" \"6\")(button :onclick \"hyprctl dispatch workspace 7\" :css \"button {color: red;}\" \"7\")(button :onclick \"hyprctl dispatch workspace 8\" \"8\")(button :onclick \"hyprctl dispatch workspace 9\" \"9\")(button :onclick \"hyprctl dispatch workspace 10\" \"10\")))" >> /tmp/hypr_sockets/active_ws ;;
        "workspace>>8") echo "(box :halign \"start\" (box (button :onclick \"hyprctl dispatch workspace 1\" \"1\")(button :onclick \"hyprctl dispatch workspace 2\" \"2\")(button :onclick \"hyprctl dispatch workspace 3\" \"3\")(button :onclick \"hyprctl dispatch workspace 4\" \"4\")(button :onclick \"hyprctl dispatch workspace 5\" \"5\")(button :onclick \"hyprctl dispatch workspace 6\" \"6\")(button :onclick \"hyprctl dispatch workspace 7\" \"7\")(button :onclick \"hyprctl dispatch workspace 8\" :css \"button {color: red;}\" \"8\")(button :onclick \"hyprctl dispatch workspace 9\" \"9\")(button :onclick \"hyprctl dispatch workspace 10\" \"10\")))" >> /tmp/hypr_sockets/active_ws ;;
        "workspace>>9") echo "(box :halign \"start\" (box (button :onclick \"hyprctl dispatch workspace 1\" \"1\")(button :onclick \"hyprctl dispatch workspace 2\" \"2\")(button :onclick \"hyprctl dispatch workspace 3\" \"3\")(button :onclick \"hyprctl dispatch workspace 4\" \"4\")(button :onclick \"hyprctl dispatch workspace 5\" \"5\")(button :onclick \"hyprctl dispatch workspace 6\" \"6\")(button :onclick \"hyprctl dispatch workspace 7\" \"7\")(button :onclick \"hyprctl dispatch workspace 8\" \"8\")(button :onclick \"hyprctl dispatch workspace 9\" :css \"button {color: red;}\" \"9\")(button :onclick \"hyprctl dispatch workspace 10\" \"10\")))" >> /tmp/hypr_sockets/active_ws ;;
        "workspace>>10") echo "(box :halign \"start\" (box (button :onclick \"hyprctl dispatch workspace 1\" \"1\")(button :onclick \"hyprctl dispatch workspace 2\" \"2\")(button :onclick \"hyprctl dispatch workspace 3\" \"3\")(button :onclick \"hyprctl dispatch workspace 4\" \"4\")(button :onclick \"hyprctl dispatch workspace 5\" \"5\")(button :onclick \"hyprctl dispatch workspace 6\" \"6\")(button :onclick \"hyprctl dispatch workspace 7\" \"7\")(button :onclick \"hyprctl dispatch workspace 8\" \"8\")(button :onclick \"hyprctl dispatch workspace 9\" \"9\")(button :onclick \"hyprctl dispatch workspace 10\" :css \"button {color: red;}\" \"10\")))" >> /tmp/hypr_sockets/active_ws ;;
            # TODO: Needs to be parsed out to check for creation of special workspaces
        createworkspace*) notify-send "$1" ;;
        destroyworkspace*) notify-send "$1" ;;
        "openlayer>>notifications") ;;
        "closelayer>>notifications") ;;
        "activewindow"*) ;;
        "windowtitle"*) ;;
        "openwindow"*) ;;
        "closewindow"*) ;;
        "submap>>") echo "" >>/tmp/hypr_sockets/active_submap ;;
        "submap>>"*) submap="$(echo "$1" | sed -E 's/(submap>>)//g')"; echo "(box :halign \"start\" \"${submap}\")" >>/tmp/hypr_sockets/active_submap ;;
        *) notify-send "$1" ;;
    esac
}

socat -U - UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock | while read -r line; do handle "$line"; done
